# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from matplotlib import rcParams
import matplotlib.font_manager as fm
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
plt.rcParams['font.sans-serif'] = ['SimHei', 'Microsoft YaHei', 'DejaVu Sans']
plt.rcParams['axes.unicode_minus'] = False

class Ui_Form(object):
    
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1385, 1155)
        Form.setStyleSheet("background-color: rgb(245, 245, 245);")
        self.gridLayout_6 = QtWidgets.QGridLayout(Form)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 50))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("background-color: #1E88E5; border-radius: 8px;background-color: rgb(30, 136, 229);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("color: white; font-size: 20px; font-weight: bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        # ==================== 用户管理模块 ====================
        self.user_group = QtWidgets.QGroupBox(Form)
        self.user_group.setMinimumSize(QtCore.QSize(0, 100))
        self.user_group.setMaximumSize(QtCore.QSize(16777215, 100))
        self.user_group.setStyleSheet("""
        QGroupBox {
            font-size: 11pt;
            font-weight: bold;
            border: 2px solid #1E88E5;
            border-radius: 8px;
            margin-top: 10px;
            padding-top: 10px;
        }
        QGroupBox::title {
            subcontrol-origin: margin;
            left: 10px;
            padding: 0 5px 0 5px;
            color: #1E88E5;
        }
        """)
        self.user_group.setObjectName("user_group")
        # 使用网格布局来组织控件
        self.user_grid_layout = QtWidgets.QGridLayout(self.user_group)
        self.user_grid_layout.setObjectName("user_grid_layout")
        self.user_grid_layout.setHorizontalSpacing(10)  
        self.user_grid_layout.setVerticalSpacing(8)       
        
        self.patient_id_label = QtWidgets.QLabel(self.user_group)
        self.patient_id_label.setMinimumSize(QtCore.QSize(60, 25))
        self.patient_id_label.setMaximumSize(QtCore.QSize(100, 25))
        self.patient_id_label.setObjectName("patient_id_label")
        self.user_grid_layout.addWidget(self.patient_id_label, 0, 0, 1, 1)

        self.patient_id_edit = QtWidgets.QLineEdit(self.user_group)
        self.patient_id_edit.setMinimumSize(QtCore.QSize(120, 25))
        self.patient_id_edit.setMaximumSize(QtCore.QSize(200, 25))
        self.patient_id_edit.setStyleSheet("border: 1px solid #BBDEFB; background-color: white; border-radius: 4px;")
        self.patient_id_edit.setObjectName("patient_id_edit")
        self.user_grid_layout.addWidget(self.patient_id_edit, 0, 1, 1, 1)
        
        self.query_user_btn = QtWidgets.QPushButton(self.user_group)
        self.query_user_btn.setMinimumSize(QtCore.QSize(80, 25))
        self.query_user_btn.setMaximumSize(QtCore.QSize(120, 25))
        self.query_user_btn.setStyleSheet("""
            QPushButton {
                background-color: #2196F3;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: #1976D2;
            }
            QPushButton:pressed {
                background-color: #1565C0;
            }
        """)
        self.query_user_btn.setObjectName("query_user_btn")
        self.query_user_btn.clicked.connect(self.query_user_info)
        self.user_grid_layout.addWidget(self.query_user_btn, 0, 2, 1, 1)
        
        self.outpatient_id_label = QtWidgets.QLabel(self.user_group)
        self.outpatient_id_label.setMinimumSize(QtCore.QSize(60, 25))
        self.outpatient_id_label.setMaximumSize(QtCore.QSize(100, 25))
        self.outpatient_id_label.setObjectName("outpatient_id_label")
        self.user_grid_layout.addWidget(self.outpatient_id_label, 0, 3, 1, 1)

        self.outpatient_id_edit = QtWidgets.QLineEdit(self.user_group)
        self.outpatient_id_edit.setMinimumSize(QtCore.QSize(120, 25))
        self.outpatient_id_edit.setMaximumSize(QtCore.QSize(200, 25))
        self.outpatient_id_edit.setStyleSheet("border: 1px solid #BBDEFB; background-color: white; border-radius: 4px;")
        self.outpatient_id_edit.setObjectName("outpatient_id_edit")
        self.user_grid_layout.addWidget(self.outpatient_id_edit, 0, 4, 1, 1)

        self.inpatient_id_label = QtWidgets.QLabel(self.user_group)
        self.inpatient_id_label.setMinimumSize(QtCore.QSize(60, 25))
        self.inpatient_id_label.setMaximumSize(QtCore.QSize(100, 25))
        self.inpatient_id_label.setObjectName("inpatient_id_label")
        self.user_grid_layout.addWidget(self.inpatient_id_label, 0, 5, 1, 1)

        self.inpatient_id_edit = QtWidgets.QLineEdit(self.user_group)
        self.inpatient_id_edit.setMinimumSize(QtCore.QSize(120, 25))
        self.inpatient_id_edit.setMaximumSize(QtCore.QSize(200, 25))
        self.inpatient_id_edit.setStyleSheet("border: 1px solid #BBDEFB; background-color: white; border-radius: 4px;")
        self.inpatient_id_edit.setObjectName("inpatient_id_edit")
        self.user_grid_layout.addWidget(self.inpatient_id_edit, 0, 6, 1, 1)

       
        self.name_label = QtWidgets.QLabel(self.user_group)
        self.name_label.setMinimumSize(QtCore.QSize(60, 25))
        self.name_label.setMaximumSize(QtCore.QSize(100, 25))
        self.name_label.setObjectName("name_label")
        self.user_grid_layout.addWidget(self.name_label, 1, 0, 1, 1)
        
        self.name_edit = QtWidgets.QLineEdit(self.user_group)
        self.name_edit.setMinimumSize(QtCore.QSize(120, 25))
        self.name_edit.setMaximumSize(QtCore.QSize(200, 25))
        self.name_edit.setStyleSheet("border: 1px solid #BBDEFB; background-color: white; border-radius: 4px;")
        self.name_edit.setObjectName("name_edit")
        self.user_grid_layout.addWidget(self.name_edit, 1, 1, 1, 1)
        
        # 身高输入
        self.height_label = QtWidgets.QLabel(self.user_group)
        self.height_label.setMinimumSize(QtCore.QSize(40, 25))
        self.height_label.setMaximumSize(QtCore.QSize(80, 25))
        self.height_label.setObjectName("height_label")
        self.user_grid_layout.addWidget(self.height_label, 1, 2, 1, 1)
        
        self.height_edit = QtWidgets.QLineEdit(self.user_group)
        self.height_edit.setMinimumSize(QtCore.QSize(80, 25))
        self.height_edit.setMaximumSize(QtCore.QSize(120, 25))
        self.height_edit.setStyleSheet("border: 1px solid #BBDEFB; background-color: white; border-radius: 4px;")
        self.height_edit.setValidator(QtGui.QDoubleValidator(0, 300, 1))
        self.height_edit.setObjectName("height_edit")
        self.user_grid_layout.addWidget(self.height_edit, 1, 3, 2, 1)
        
        self.weight_label = QtWidgets.QLabel(self.user_group)
        self.weight_label.setMinimumSize(QtCore.QSize(40, 25))
        self.weight_label.setMaximumSize(QtCore.QSize(80, 25))
        self.weight_label.setObjectName("weight_label")
        self.user_grid_layout.addWidget(self.weight_label, 1, 4, 1, 1)
        
        self.weight_edit = QtWidgets.QLineEdit(self.user_group)
        self.weight_edit.setMinimumSize(QtCore.QSize(80, 25))
        self.weight_edit.setMaximumSize(QtCore.QSize(120, 25))
        self.weight_edit.setStyleSheet("border: 1px solid #BBDEFB; background-color: white; border-radius: 4px;")
        self.weight_edit.setValidator(QtGui.QDoubleValidator(0, 300, 1))
        self.weight_edit.setObjectName("weight_edit")
        self.user_grid_layout.addWidget(self.weight_edit, 1, 5, 1, 1)
        
        self.gender_label = QtWidgets.QLabel(self.user_group)
        self.gender_label.setMinimumSize(QtCore.QSize(40, 25))
        self.gender_label.setMaximumSize(QtCore.QSize(80, 25))
        self.gender_label.setObjectName("gender_label")
        self.user_grid_layout.addWidget(self.gender_label, 1, 6, 1, 1)
        
        self.gender_combo = QtWidgets.QComboBox(self.user_group)
        self.gender_combo.setMinimumSize(QtCore.QSize(80, 25))
        self.gender_combo.setMaximumSize(QtCore.QSize(120, 25))
        self.gender_combo.setStyleSheet("""
            QComboBox {
                border: 1px solid #BBDEFB;
                background-color: white;
                border-radius: 4px;
                padding: 3px 5px;
                min-width: 80px;
                }
            QComboBox:hover {
                border-color: #64B5F6;
                }                        
        """)
        self.gender_combo.addItems(["男", "女"])
        self.gender_combo.setCurrentIndex(0) 
        self.gender_combo.setObjectName("gender_combo")
        self.user_grid_layout.addWidget(self.gender_combo, 1, 7, 1, 1)

        self.age_label = QtWidgets.QLabel(self.user_group)
        self.age_label.setMinimumSize(QtCore.QSize(40, 25))
        self.age_label.setMaximumSize(QtCore.QSize(80, 25))
        self.age_label.setObjectName("age_label")
        self.user_grid_layout.addWidget(self.age_label, 1, 8, 1, 1)
        
        self.age_edit = QtWidgets.QLineEdit(self.user_group)
        self.age_edit.setMinimumSize(QtCore.QSize(80, 25))
        self.age_edit.setMaximumSize(QtCore.QSize(120, 25))
        self.age_edit.setStyleSheet("border: 1px solid #BBDEFB; background-color: white; border-radius: 4px;")
        self.age_edit.setValidator(QtGui.QDoubleValidator(0, 110, 1))
        self.age_edit.setObjectName("age_edit")
        self.user_grid_layout.addWidget(self.age_edit, 1, 9, 1, 1)

        self.save_user_btn = QtWidgets.QPushButton(self.user_group)
        self.save_user_btn.setMinimumSize(QtCore.QSize(80, 25))
        self.save_user_btn.setMaximumSize(QtCore.QSize(120, 25))
        self.save_user_btn.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: #43A047;
            }
            QPushButton:pressed {
                background-color: #388E3C;
            }
        """)
        self.save_user_btn.setObjectName("save_user_btn")
        self.user_grid_layout.addWidget(self.save_user_btn, 1, 10, 1, 1)
        self.save_user_btn.clicked.connect(self.save_user_info)
        
        self.clear_user_btn = QtWidgets.QPushButton(self.user_group)
        self.clear_user_btn.setMinimumSize(QtCore.QSize(80, 25))
        self.clear_user_btn.setMaximumSize(QtCore.QSize(120, 25))
        self.clear_user_btn.setStyleSheet("""
            QPushButton {
                background-color: #FF9800;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: #F57C00;
            }
            QPushButton:pressed {
                background-color: #E65100;
            }
        """)
        self.clear_user_btn.setObjectName("clear_user_btn")
        self.clear_user_btn.clicked.connect(self.clear_user_form)
        self.user_grid_layout.addWidget(self.clear_user_btn, 1, 11, 1, 1)
        
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.user_group)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setStyleSheet("font-size: 11pt ;font-weight: bold;")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(100, 30))
        self.label_2.setMaximumSize(QtCore.QSize(1000, 30))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.port_combo = QtWidgets.QComboBox(self.groupBox)
        self.port_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.port_combo.setMaximumSize(QtCore.QSize(2000, 30))
        self.port_combo.setStyleSheet("border: 1px solid lightblue;background-color: rgb(255, 255, 255);")
        self.port_combo.setObjectName("port_combo")
        self.horizontalLayout.addWidget(self.port_combo)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(100, 30))
        self.label_3.setMaximumSize(QtCore.QSize(1000, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.baudrate_combo = QtWidgets.QComboBox(self.groupBox)
        self.baudrate_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.baudrate_combo.setMaximumSize(QtCore.QSize(2000, 303))
        self.baudrate_combo.setStyleSheet("border: 1px solid lightblue;background-color: rgb(255, 255, 255);")
        self.baudrate_combo.setObjectName("baudrate_combo")
        self.horizontalLayout.addWidget(self.baudrate_combo)
        self.connect_btn = QtWidgets.QPushButton(self.groupBox)
        self.connect_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.connect_btn.setMaximumSize(QtCore.QSize(2000, 30))
        self.connect_btn.setStyleSheet("QPushButton {\n"
        "                background-color: #1E88E5;\n"
        "                border-radius: 5px;\n"
        "                padding: 6px 12px;\n"
        "    color: rgb(255, 255, 255);\n"
        "            }\n"
        "QPushButton:hover {\n"
        "                background-color: #1976D2;\n"
        "            }\n"
        "QPushButton:pressed {\n"
        "                background-color: #1565C0;}")
        self.connect_btn.setObjectName("connect_btn")
        self.horizontalLayout.addWidget(self.connect_btn)
        self.status_label = QtWidgets.QLabel(self.groupBox)
        self.status_label.setMinimumSize(QtCore.QSize(150, 30))
        self.status_label.setMaximumSize(QtCore.QSize(1500, 30))
        self.status_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.status_label.setObjectName("status_label")
        self.horizontalLayout.addWidget(self.status_label)

        self.verticalLayout.addWidget(self.groupBox)
        
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 280))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 280))
        self.groupBox_2.setStyleSheet("font-weight: bold;\n"
        "font-size: 11pt ;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox1.setChecked(False)
        self.checkBox1.setObjectName("checkBox1")
        self.gridLayout_2.addWidget(self.checkBox1, 0, 0, 1, 1)
        self.checkBox2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox2.setChecked(False)
        self.checkBox2.setObjectName("checkBox2")
        self.gridLayout_2.addWidget(self.checkBox2, 1, 0, 1, 1)
        self.checkBox3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox3.setChecked(False)
        self.checkBox3.setObjectName("checkBox3")
        self.gridLayout_2.addWidget(self.checkBox3, 2, 0, 1, 1)
        self.checkBox4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox4.setChecked(False)
        self.checkBox4.setObjectName("checkBox4")
        self.gridLayout_2.addWidget(self.checkBox4, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 0, 0, 1, 1)

        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.checkBox5 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox5.setChecked(False)
        self.checkBox5.setObjectName("checkBox5")
        self.gridLayout_10.addWidget(self.checkBox5, 0, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.QYsetA_text = QtWidgets.QLineEdit(self.groupBox_5)
        self.QYsetA_text.setMinimumSize(QtCore.QSize(40, 25))
        self.QYsetA_text.setMaximumSize(QtCore.QSize(40, 25))
        self.QYsetA_text.setStyleSheet("background-color: white;")
        self.QYsetA_text.setReadOnly(False)  
        validator = QtGui.QIntValidator(20, 300, self.QYsetA_text)
        self.QYsetA_text.setValidator(validator)
        self.QYsetA_text.setObjectName("QYsetA_text")
        self.gridLayout_10.addWidget(self.QYsetA_text, 1, 1, 1, 1)  

        self.QYsetA_error = QtWidgets.QLabel(self.groupBox_5)
        self.QYsetA_error.setMinimumSize(QtCore.QSize(300, 20))
        self.QYsetA_error.setMaximumSize(QtCore.QSize(300, 20))
        self.QYsetA_error.setStyleSheet("color: red;")
        self.QYsetA_error.setText("")  # 初始为空
        self.gridLayout_10.addWidget(self.QYsetA_error, 1, 2, 1, 3)  # 放在第2行第3列

        self.QYsetA_label = QtWidgets.QLabel("左上肢压力:", self.groupBox_5)
        self.gridLayout_10.addWidget(self.QYsetA_label, 1, 0, 1, 1)
                

        self.QYsetB_text = QtWidgets.QLineEdit(self.groupBox_5)
        self.QYsetB_text.setMinimumSize(QtCore.QSize(40, 25))
        self.QYsetB_text.setMaximumSize(QtCore.QSize(40, 25))
        self.QYsetB_text.setStyleSheet("background-color: white;")
        self.QYsetB_text.setReadOnly(False)
        validator = QtGui.QIntValidator(20, 300, self.QYsetB_text)
        self.QYsetB_text.setValidator(validator)
        self.QYsetB_text.setObjectName("QYsetB_text")
        self.gridLayout_10.addWidget(self.QYsetB_text, 2, 1, 1, 1)  # 第3行第2列

        self.QYsetB_error = QtWidgets.QLabel(self.groupBox_5)
        self.QYsetB_error.setMinimumSize(QtCore.QSize(300, 20))
        self.QYsetB_error.setMaximumSize(QtCore.QSize(300, 20))
        self.QYsetB_error.setStyleSheet("color: red;")
        self.QYsetB_error.setText("")  # 初始为空
        self.gridLayout_10.addWidget(self.QYsetB_error, 2, 2, 1, 4)
        

        self.QYsetC_text = QtWidgets.QLineEdit(self.groupBox_5)
        self.QYsetC_text.setMinimumSize(QtCore.QSize(40, 25))
        self.QYsetC_text.setMaximumSize(QtCore.QSize(40, 25))
        self.QYsetC_text.setStyleSheet("background-color: white;")
        self.QYsetC_text.setReadOnly(False)
        validator = QtGui.QIntValidator(20, 300, self.QYsetC_text)
        self.QYsetC_text.setValidator(validator)
        self.QYsetC_text.setObjectName("QYsetC_text")
        self.gridLayout_10.addWidget(self.QYsetC_text, 3, 1, 1, 1)  # 第4行第2列

        self.QYsetC_error = QtWidgets.QLabel(self.groupBox_5)
        self.QYsetC_error.setMinimumSize(QtCore.QSize(300, 20))
        self.QYsetC_error.setMaximumSize(QtCore.QSize(300, 20))
        self.QYsetC_error.setStyleSheet("color: red;")
        self.QYsetC_error.setText("")  # 初始为空
        self.gridLayout_10.addWidget(self.QYsetC_error, 3, 2, 1, 4)

        self.QYsetD_text = QtWidgets.QLineEdit(self.groupBox_5)
        self.QYsetD_text.setMinimumSize(QtCore.QSize(40, 25))
        self.QYsetD_text.setMaximumSize(QtCore.QSize(40, 25))
        self.QYsetD_text.setStyleSheet("background-color: white;")
        self.QYsetD_text.setReadOnly(False)
        validator = QtGui.QIntValidator(20, 300, self.QYsetD_text)
        self.QYsetD_text.setValidator(validator)
        self.QYsetD_text.setObjectName("QYsetD_text")
        self.gridLayout_10.addWidget(self.QYsetD_text, 4, 1, 1, 1)  # 第5行第2列

        self.QYsetD_error = QtWidgets.QLabel(self.groupBox_5)
        self.QYsetD_error.setMinimumSize(QtCore.QSize(300, 20))
        self.QYsetD_error.setMaximumSize(QtCore.QSize(300, 20))
        self.QYsetD_error.setStyleSheet("color: red;")
        self.QYsetD_error.setText("")  # 初始为空
        self.gridLayout_10.addWidget(self.QYsetD_error, 4, 2, 1, 4)  # 放在第5行第3列

        # 连接信号到验证函数
        self.QYsetA_text.textChanged.connect(lambda: self.validate_pressure_input(self.QYsetA_text, self.QYsetA_error, 20, 300))
        self.QYsetB_text.textChanged.connect(lambda: self.validate_pressure_input(self.QYsetB_text, self.QYsetB_error, 20, 300))
        self.QYsetC_text.textChanged.connect(lambda: self.validate_pressure_input(self.QYsetC_text, self.QYsetC_error, 20, 300))
        self.QYsetD_text.textChanged.connect(lambda: self.validate_pressure_input(self.QYsetD_text, self.QYsetD_error, 20, 300))


        self.QYsetA_label = QtWidgets.QLabel("左上肢压力:", self.groupBox_5)
        self.gridLayout_10.addWidget(self.QYsetA_label, 1, 0, 1, 1)  # 第2行第1列

        self.QYsetB_label = QtWidgets.QLabel("左下肢压力:", self.groupBox_5)
        self.gridLayout_10.addWidget(self.QYsetB_label, 2, 0, 1, 1)  # 第3行第1列

        self.QYsetC_label = QtWidgets.QLabel("右上肢压力:", self.groupBox_5)
        self.gridLayout_10.addWidget(self.QYsetC_label, 3, 0, 1, 1)  # 第4行第1列

        self.QYsetD_label = QtWidgets.QLabel("右下肢压力:", self.groupBox_5)
        self.gridLayout_10.addWidget(self.QYsetD_label, 4, 0, 1, 1)  # 第5行第1列


        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")

        self.query_wave_amp_btn = QtWidgets.QPushButton("查询")
        self.query_wave_amp_btn.setStyleSheet("QPushButton {\n"
        "    background-color: #2196F3;\n"
        "    border-radius: 6px;\n"
        "    color: white;\n"
        "    padding: 6px 6px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "    background-color: #1976D2;\n"
        "}\n"
        "QPushButton:pressed {\n"
        "    background-color: #1565C0;\n"
        "}")
        self.query_wave_amp_btn.setObjectName("query_wave_amp_btn")
        self.gridLayout_11.addWidget(self.query_wave_amp_btn, 0, 0, 2, 1)    
        self.carotid_label = QtWidgets.QLabel("1",self.groupBox_6)
        self.carotid_label.setText("颈动脉")
        self.gridLayout_11.addWidget(self.carotid_label, 2, 0, 1, 1)
        self.femoral_label = QtWidgets.QLabel("1",self.groupBox_6)
        self.femoral_label.setText("股动脉")
        self.gridLayout_11.addWidget(self.femoral_label, 3, 0, 1, 1)
        # 返回值显示文本框1
        self.carotid_result_text = QtWidgets.QTextEdit(self.groupBox_6)
        self.carotid_result_text.setMinimumSize(QtCore.QSize(200, 40))
        self.carotid_result_text.setMaximumSize(QtCore.QSize(200, 40))
        self.carotid_result_text.setStyleSheet("background-color: white;")
        self.carotid_result_text.setReadOnly(True)
        self.carotid_result_text.setObjectName("carotid_result_text")
        self.gridLayout_11.addWidget(self.carotid_result_text, 2, 1, 1, 1)

        # 返回值显示文本框2
        self.femoral_result_text = QtWidgets.QTextEdit(self.groupBox_6)
        self.femoral_result_text.setMinimumSize(QtCore.QSize(200, 40))
        self.femoral_result_text.setMaximumSize(QtCore.QSize(200, 40))
        self.femoral_result_text.setStyleSheet("background-color: white;")
        self.femoral_result_text.setReadOnly(True)
        self.femoral_result_text.setObjectName("femoral_result_text")
        self.gridLayout_11.addWidget(self.femoral_result_text, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_6, 0, 2, 1, 1)

        self.query_wave_amp_btn.clicked.connect(self.on_query_wave_amplitude)

        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        
        # 添加波形放大倍数调整控件
        # 颈动脉放大倍数标签
        self.carotid_amp_label = QtWidgets.QLabel("1",self.groupBox_7)
        self.carotid_amp_label.setText("颈动脉放大倍数:")
        self.gridLayout_12.addWidget(self.carotid_amp_label, 1, 0, 1, 1)
        
        # 颈动脉放大倍数滚动条
        self.carotid_amp_slider = QtWidgets.QSlider(self.groupBox_7)
        self.carotid_amp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.carotid_amp_slider.setGeometry(110, 30, 100, 20) 
        self.carotid_amp_slider.setRange(1, 15)
        self.carotid_amp_slider.setValue(1)  # 默认值
        self.carotid_amp_slider.setSingleStep(1) # 设置步长
        self.gridLayout_12.addWidget(self.carotid_amp_slider, 1, 1, 1, 1)
        
        # 颈动脉放大倍数数值显示
        self.carotid_amp_value = QtWidgets.QLabel("1",self.groupBox_7)
        self.gridLayout_12.addWidget(self.carotid_amp_value, 1, 2, 1, 1)
        
        # 股动脉放大倍数标签
        self.femoral_amp_label = QtWidgets.QLabel(self.groupBox_7)
        self.femoral_amp_label.setText("股动脉放大倍数:")
        self.gridLayout_12.addWidget(self.femoral_amp_label, 2, 0, 1, 1)
        
        # 股动脉放大倍数滚动条
        self.femoral_amp_slider = QtWidgets.QSlider(self.groupBox_7)
        self.femoral_amp_slider.setOrientation(QtCore.Qt.Horizontal)
        self.femoral_amp_slider.setRange(1,15)
        self.femoral_amp_slider.setValue(1)
        self.gridLayout_12.addWidget(self.femoral_amp_slider, 2, 1, 1, 1)
        
        
        # 股动脉放大倍数数值显示
        self.femoral_amp_value = QtWidgets.QLabel("1",self.groupBox_7)
        self.gridLayout_12.addWidget(self.femoral_amp_value, 2, 2, 1, 1)
        
        # 连接滚动条值改变信号到槽函数
        self.carotid_amp_slider.valueChanged.connect(self.update_carotid_amp_display)
        self.femoral_amp_slider.valueChanged.connect(self.update_femoral_amp_display)

        self.gridLayout_5.addWidget(self.groupBox_7, 0, 3, 1, 1)

        # 波形倍数调整
        self.adj_wave_amp_btn = QtWidgets.QPushButton("调整")
        self.adj_wave_amp_btn.setStyleSheet("QPushButton {\n"
        "    background-color: #2196F3;\n"
        "    border-radius: 6px;\n"
        "    color: white;\n"
        "    padding: 6px 6px;\n"
        "}\n"
        "QPushButton:hover {\n"
        "    background-color: #1976D2;\n"
        "}\n"
        "QPushButton:pressed {\n"
        "    background-color: #1565C0;\n"
        "}")
        self.adj_wave_amp_btn.setObjectName("adj_wave_amp_btn")
        self.gridLayout_12.addWidget(self.adj_wave_amp_btn, 3, 0, 1, 1)  
        self.adj_wave_amp_btn.clicked.connect(self.on_adjust_wave_amplitude)
        
        #调整返回文本框
        self.adj_result_text = QtWidgets.QTextEdit(self.groupBox_7)
        self.adj_result_text.setMinimumSize(QtCore.QSize(300, 100))
        self.adj_result_text.setMaximumSize(QtCore.QSize(300, 100))
        self.adj_result_text.setStyleSheet("background-color: white;")
        self.adj_result_text.setReadOnly(True)
        self.adj_result_text.setObjectName("adj_result_text")
        self.gridLayout_12.addWidget(self.adj_result_text, 3, 1, 1, 1)

        #颈股动脉查询
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.checkBox6 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox6.setChecked(False)
        self.checkBox6.setObjectName("checkBox6")
        self.gridLayout_13.addWidget(self.checkBox6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_8, 0, 4, 1, 1)

        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.start_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.start_btn.setStyleSheet("QPushButton {\n"
"                background-color: #4CAF50;\n"
"                border-radius: 5px;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #43A047;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #388E3C;\n"
"            }")
        self.start_btn.setObjectName("start_btn")
        self.gridLayout_3.addWidget(self.start_btn, 0, 0, 1, 1)
        self.double_mode_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.double_mode_btn.setStyleSheet("""
        QPushButton {
                background-color: #FF9800;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 8px 16px;
        }
        QPushButton:hover {
                background-color: #F57C00;
        }
        QPushButton:pressed {
                background-color: #E65100;
        }
        """)
        self.double_mode_btn.setObjectName("double_mode_btn")
        
        self.gridLayout_3.addWidget(self.double_mode_btn, 1, 0, 1, 1)
        self.stop_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.stop_btn.setStyleSheet("QPushButton {\n"
"                background-color: #F44336;\n"
"                border-radius: 5px;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #D32F2F;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #C62828;\n"
"            }")
        self.stop_btn.setObjectName("stop_btn")
        self.gridLayout_3.addWidget(self.stop_btn, 2, 0, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.clear_btn.setStyleSheet("QPushButton {\n"
"                background-color: #FF9800;\n"
"                border-radius: 5px;\n"
"                color: white;\n"
"                font-weight: bold;\n"
"                padding: 8px 16px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: #F57C00;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: #E65100;\n"
"            }")
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout_3.addWidget(self.clear_btn, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 0, 5, 1, 1)

        self.box_frame_rate= QtWidgets.QGroupBox(self.groupBox_2)
        self.box_frame_rate.setObjectName("box_frame_rate")
        self.gridLayout_5.addWidget(self.box_frame_rate, 0, 6, 1, 1)
        self.gridLayout_box_fr = QtWidgets.QGridLayout(self.box_frame_rate)
        self.gridLayout_box_fr.setObjectName("gridLayout_box_fr")
        self.limbs_label = QtWidgets.QLabel("1",self.box_frame_rate)
        self.limbs_label.setText("脉搏波模块")
        self.gridLayout_box_fr.addWidget(self.limbs_label, 1, 0, 1, 1)
        self.ecg_label = QtWidgets.QLabel("1",self.box_frame_rate)
        self.ecg_label.setText("心电模块")
        self.gridLayout_box_fr.addWidget(self.ecg_label, 2, 0, 1, 1)
        self.heart_sound_fr_label = QtWidgets.QLabel("1",self.box_frame_rate)
        self.heart_sound_fr_label.setText("心音模块")
        self.gridLayout_box_fr.addWidget(self.heart_sound_fr_label , 3, 0, 1, 1)
        self.carotid_femoral_label = QtWidgets.QLabel("1",self.box_frame_rate)
        self.carotid_femoral_label.setText("颈股动脉模块")
        self.gridLayout_box_fr.addWidget(self.carotid_femoral_label, 4, 0, 1, 1)
        
        self.limbs_frame_rate_text = QtWidgets.QTextEdit(self.box_frame_rate)
        self.limbs_frame_rate_text.setMinimumSize(QtCore.QSize(150, 30))
        self.limbs_frame_rate_text.setMaximumSize(QtCore.QSize(150, 30))
        self.limbs_frame_rate_text.setStyleSheet("background-color: white;")
        self.limbs_frame_rate_text.setReadOnly(True)
        self.limbs_frame_rate_text.setObjectName("limbs_frame_rate_text")
        self.gridLayout_box_fr.addWidget(self.limbs_frame_rate_text, 1, 1, 1, 1)
        self.ecg_frame_rate_text = QtWidgets.QTextEdit(self.box_frame_rate)
        self.ecg_frame_rate_text.setMinimumSize(QtCore.QSize(150, 30))
        self.ecg_frame_rate_text.setMaximumSize(QtCore.QSize(150, 30))
        self.ecg_frame_rate_text.setStyleSheet("background-color: white;")
        self.ecg_frame_rate_text.setReadOnly(True)
        self.ecg_frame_rate_text.setObjectName("ecg_frame_rate_text")
        self.gridLayout_box_fr.addWidget(self.ecg_frame_rate_text, 2, 1, 1, 1)
        self.hs_frame_rate_text = QtWidgets.QTextEdit(self.box_frame_rate)
        self.hs_frame_rate_text.setMinimumSize(QtCore.QSize(150, 30))
        self.hs_frame_rate_text.setMaximumSize(QtCore.QSize(150, 30))
        self.hs_frame_rate_text.setStyleSheet("background-color: white;")
        self.hs_frame_rate_text.setReadOnly(True)
        self.hs_frame_rate_text.setObjectName("ecg_frame_rate_text")
        self.gridLayout_box_fr.addWidget(self.hs_frame_rate_text, 3, 1, 1, 1)
        self.cf_frame_rate_text = QtWidgets.QTextEdit(self.box_frame_rate)
        self.cf_frame_rate_text.setMinimumSize(QtCore.QSize(150, 30))
        self.cf_frame_rate_text.setMaximumSize(QtCore.QSize(150, 30))
        self.cf_frame_rate_text.setStyleSheet("background-color: white;")
        self.cf_frame_rate_text.setReadOnly(True)
        self.cf_frame_rate_text.setObjectName("cf_frame_rate_text")
        self.gridLayout_box_fr.addWidget(self.cf_frame_rate_text, 4, 1, 1, 1)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"                border: none;\n"
"                background-color: #F5F5F5;\n"
"\n"
"                \n"
"            }\n"
"            QTabBar::tab {\n"
"                background-color: #E3F2FD;\n"
"                border: 1px solid #BBDEFB;\n"
"                border-bottom: none;\n"
"                border-top-left-radius: 4px;\n"
"                border-top-right-radius: 4px;\n"
"                padding: 6px 12px;\n"
"                font-weight: bold;\n"
"\n"
"            }\n"
"            QTabBar::tab:selected {\n"
"                background-color: #1E88E5;\n"
"                color: white;\n"
"                border-color: #1976D2;\n"
"\n"
"            }\n"
"            QTabBar::tab:hover {\n"
"                background-color: #BBDEFB;\n"
"\n"
"            }")
        self.tabWidget.setObjectName("tabWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.horizontalLayout_7.addLayout(self.verticalLayout_4)


        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_6.addWidget(self.label_14)
        self.tableWidget1 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(3)
        self.tableWidget1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        self.verticalLayout_6.addWidget(self.tableWidget1)
        self.gridLayout_8.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.tableWidget2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(3)
        self.tableWidget2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(2, item)
        self.verticalLayout_7.addWidget(self.tableWidget2)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 0, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_8.addWidget(self.label_16)
        self.tableWidget3 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget3.setObjectName("tableWidget3")
        self.tableWidget3.setColumnCount(3)
        self.tableWidget3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget3.setHorizontalHeaderItem(2, item)
        self.verticalLayout_8.addWidget(self.tableWidget3)
        self.gridLayout_8.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_9.addWidget(self.label_17)
        self.tableWidget4 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget4.setObjectName("tableWidget4")
        self.tableWidget4.setColumnCount(3)
        self.tableWidget4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget4.setHorizontalHeaderItem(2, item)
        self.verticalLayout_9.addWidget(self.tableWidget4)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")

        self.tab_inflation_process = QtWidgets.QWidget()
        self.tab_inflation_process.setObjectName("tab_inflation_process")
        self.layout_tab_inflation = QtWidgets.QVBoxLayout(self.tab_inflation_process)
        self.layout_tab_inflation.setContentsMargins(10, 10, 10, 10)
        self.layout_tab_inflation.setSpacing(10)

        self.inflation_display_text = QtWidgets.QTextEdit(self.tab_inflation_process)
        self.inflation_display_text.setSizePolicy(
            QtWidgets.QSizePolicy.Expanding,
            QtWidgets.QSizePolicy.Expanding
        )
        self.inflation_display_text.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.inflation_display_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.inflation_display_text.setStyleSheet("""
            QTextEdit {
                background-color: white;
                border: 1px solid #BBDEFB;
                border-radius: 4px;
                font-family: "Microsoft YaHei", "SimHei";
                font-size: 12px;
                padding: 10px;
            }
            /* 可选：自定义滚动条样式 */
            QTextEdit QScrollBar:vertical {
                width: 12px;
                background-color: #F5F5F5;
            }
            QTextEdit QScrollBar::handle:vertical {
                background-color: #BDBDBD;
                border-radius: 6px;
                min-height: 20px;
            }
        """)
        self.inflation_display_text.setReadOnly(True)
        self.inflation_display_text.setPlaceholderText("打气过程中的血压值将显示在这里...")
        self.layout_tab_inflation.addWidget(self.inflation_display_text)
        self.tabWidget.addTab(self.tab_inflation_process, "测量过程")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layout_tab2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.layout_tab2.setContentsMargins(10, 10, 10, 10)
        self.layout_tab2.setSpacing(15)
        self.scroll_area_limbs = QtWidgets.QScrollArea()
        self.scroll_area_limbs.setWidgetResizable(True)
        self.scroll_area_limbs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area_limbs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area_limbs.setStyleSheet("""
            QScrollArea {
                border: none;
                background-color: transparent;
            }
            QScrollBar:vertical {
                background-color: #F5F5F5;
                width: 12px;
                margin: 0px;
            }
            QScrollBar::handle:vertical {
                background-color: #BDBDBD;
                border-radius: 6px;
                min-height: 20px;
            }
            QScrollBar::handle:vertical:hover {
                background-color: #9E9E9E;
            }
        """)

        self.scroll_content = QtWidgets.QWidget()
        self.scroll_layout = QtWidgets.QVBoxLayout(self.scroll_content)
        self.scroll_layout.setContentsMargins(5, 5, 5, 5)
        self.scroll_layout.setSpacing(15)
        self.frame_upper_left = QtWidgets.QFrame()
        self.frame_upper_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_upper_left.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.frame_upper_left.setMinimumHeight(400)
        self.layout_upper_left = QtWidgets.QVBoxLayout(self.frame_upper_left)
        self.layout_upper_left.setContentsMargins(10, 10, 10, 10)

        self.title_upper_left = QtWidgets.QLabel("左上肢脉搏波")
        self.title_upper_left.setStyleSheet("""
            QLabel {
                font-size: 14px;
                font-weight: bold;
                color: #0D47A1;
                padding: 8px;
                background-color: #E3F2FD;
                border-radius: 3px;
                text-align: center;
            }
        """)
        self.title_upper_left.setAlignment(QtCore.Qt.AlignCenter)
        self.layout_upper_left.addWidget(self.title_upper_left)

        self.fig_limb_upper_left = Figure(figsize=(12, 6), dpi=100) 
        self.canvas_limb_upper_left = FigureCanvas(self.fig_limb_upper_left)
        self.ax_limb_upper_left = self.fig_limb_upper_left.add_subplot(111)
        self.ax_limb_upper_left.set_title("", fontsize=12)
        self.ax_limb_upper_left.grid(True, alpha=0.3)
        self.ax_limb_upper_left.tick_params(axis='both', which='major', labelsize=9)
        self.fig_limb_upper_left.tight_layout(pad=3.0)
        self.layout_upper_left.addWidget(self.canvas_limb_upper_left)

        self.scroll_layout.addWidget(self.frame_upper_left)
        self.frame_lower_left = QtWidgets.QFrame()
        self.frame_lower_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lower_left.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.frame_lower_left.setMinimumHeight(400)
        self.layout_lower_left = QtWidgets.QVBoxLayout(self.frame_lower_left)
        self.layout_lower_left.setContentsMargins(10, 10, 10, 10)

        self.title_lower_left = QtWidgets.QLabel("左下肢脉搏波")
        self.title_lower_left.setStyleSheet("""
            QLabel {
                font-size: 14px;
                font-weight: bold;
                color: #0D47A1;
                padding: 8px;
                background-color: #E3F2FD;
                border-radius: 3px;
                text-align: center;
            }
        """)
        self.title_lower_left.setAlignment(QtCore.Qt.AlignCenter)
        self.layout_lower_left.addWidget(self.title_lower_left)

        self.fig_limb_lower_left = Figure(figsize=(12, 6), dpi=100)
        self.canvas_limb_lower_left = FigureCanvas(self.fig_limb_lower_left)
        self.ax_limb_lower_left = self.fig_limb_lower_left.add_subplot(111)
        self.ax_limb_lower_left.set_title("", fontsize=12)
        self.ax_limb_lower_left.grid(True, alpha=0.3)
        self.ax_limb_lower_left.tick_params(axis='both', which='major', labelsize=9)
        self.fig_limb_lower_left.tight_layout(pad=3.0)
        self.layout_lower_left.addWidget(self.canvas_limb_lower_left)

        self.scroll_layout.addWidget(self.frame_lower_left)

        self.frame_upper_right = QtWidgets.QFrame()
        self.frame_upper_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_upper_right.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.frame_upper_right.setMinimumHeight(400)
        self.layout_upper_right = QtWidgets.QVBoxLayout(self.frame_upper_right)
        self.layout_upper_right.setContentsMargins(10, 10, 10, 10)

        self.title_upper_right = QtWidgets.QLabel("右上肢脉搏波")
        self.title_upper_right.setStyleSheet("""
            QLabel {
                font-size: 14px;
                font-weight: bold;
                color: #0D47A1;
                padding: 8px;
                background-color: #E3F2FD;
                border-radius: 3px;
                text-align: center;
            }
        """)
        self.title_upper_right.setAlignment(QtCore.Qt.AlignCenter)
        self.layout_upper_right.addWidget(self.title_upper_right)

        self.fig_limb_upper_right = Figure(figsize=(12, 6), dpi=100)
        self.canvas_limb_upper_right = FigureCanvas(self.fig_limb_upper_right)
        self.ax_limb_upper_right = self.fig_limb_upper_right.add_subplot(111)
        self.ax_limb_upper_right.set_title("", fontsize=12)
        self.ax_limb_upper_right.grid(True, alpha=0.3)
        self.ax_limb_upper_right.tick_params(axis='both', which='major', labelsize=9)
        self.fig_limb_upper_right.tight_layout(pad=3.0)
        self.layout_upper_right.addWidget(self.canvas_limb_upper_right)

        self.scroll_layout.addWidget(self.frame_upper_right)

        self.frame_lower_right = QtWidgets.QFrame()
        self.frame_lower_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_lower_right.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.frame_lower_right.setMinimumHeight(400)
        self.layout_lower_right = QtWidgets.QVBoxLayout(self.frame_lower_right)
        self.layout_lower_right.setContentsMargins(10, 10, 10, 10)

        self.title_lower_right = QtWidgets.QLabel("右下肢脉搏波")
        self.title_lower_right.setStyleSheet("""
            QLabel {
                font-size: 14px;
                font-weight: bold;
                color: #0D47A1;
                padding: 8px;
                background-color: #E3F2FD;
                border-radius: 3px;
                text-align: center;
            }
        """)
        self.title_lower_right.setAlignment(QtCore.Qt.AlignCenter)
        self.layout_lower_right.addWidget(self.title_lower_right)

        self.fig_limb_lower_right = Figure(figsize=(12, 6), dpi=100)
        self.canvas_limb_lower_right = FigureCanvas(self.fig_limb_lower_right)
        self.ax_limb_lower_right = self.fig_limb_lower_right.add_subplot(111)
        self.ax_limb_lower_right.set_title("", fontsize=12)
        self.ax_limb_lower_right.grid(True, alpha=0.3)
        self.ax_limb_lower_right.tick_params(axis='both', which='major', labelsize=9)
        self.fig_limb_lower_right.tight_layout(pad=3.0)
        self.layout_lower_right.addWidget(self.canvas_limb_lower_right)

        self.scroll_layout.addWidget(self.frame_lower_right)
        self.scroll_layout.addStretch(1)
        self.scroll_area_limbs.setWidget(self.scroll_content)
        self.layout_tab2.addWidget(self.scroll_area_limbs)
        self.tabWidget.addTab(self.tab_2, "四肢脉搏波")
        self.gridLayout_6.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.tab_ecg = QtWidgets.QWidget()
        self.tab_ecg.setObjectName("tab_ecg")
        self.layout_tab_ecg = QtWidgets.QVBoxLayout(self.tab_ecg)
        self.layout_tab_ecg.setContentsMargins(10, 10, 10, 10)
        self.layout_tab_ecg.setSpacing(10)
        
        self.ecg_frame = QtWidgets.QFrame()
        self.ecg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ecg_frame.setStyleSheet("""
            QFrame {
                background-color: white; 
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.ecg_layout = QtWidgets.QVBoxLayout(self.ecg_frame)
        self.ecg_layout.setContentsMargins(10, 10, 10, 10)
        self.ecg_layout.setSpacing(8)
       
        self.fig_ecg = Figure(figsize=(12, 6), dpi=100)
        self.canvas_ecg = FigureCanvas(self.fig_ecg)
        self.ax_ecg = self.fig_ecg.add_subplot(111)
        self.ax_ecg.set_title("心电图信号", fontsize=10)
        self.ax_ecg.grid(True, alpha=0.3)
        self.ax_ecg.tick_params(axis='both', which='major', labelsize=9)
        self.fig_ecg.subplots_adjust(left=0.12, bottom=0.15, right=0.95, top=0.9)
        self.fig_ecg.tight_layout(pad=3.0)
        self.ecg_layout.addWidget(self.canvas_ecg)
        self.layout_tab_ecg.addWidget(self.ecg_frame)
        self.layout_tab_ecg.addStretch(1)
        self.tabWidget.addTab(self.tab_ecg, "心电监测")
        self.gridLayout_6.addWidget(self.tabWidget, 2, 0, 1, 1)
        
        self.tab_pcg = QtWidgets.QWidget()
        self.tab_pcg.setObjectName("tab_pcg")
        self.layout_tab_pcg = QtWidgets.QVBoxLayout(self.tab_pcg)
        self.layout_tab_pcg.setContentsMargins(10, 10, 10, 10)
        self.layout_tab_pcg.setSpacing(10)
       
        self.pcg_frame = QtWidgets.QFrame()
        self.pcg_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pcg_frame.setStyleSheet("""
            QFrame {
                background-color: white; 
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.pcg_layout = QtWidgets.QVBoxLayout(self.pcg_frame)
        self.pcg_layout.setContentsMargins(10, 10, 10, 10)
        self.pcg_layout.setSpacing(8)
       
        self.fig_pcg = Figure(figsize=(12, 6), dpi=100)
        self.canvas_pcg = FigureCanvas(self.fig_pcg)
        self.ax_pcg = self.fig_pcg.add_subplot(111)
        self.ax_pcg.set_title("心音图信号", fontsize=10)
        self.ax_pcg.grid(True, alpha=0.3)
        self.ax_pcg.tick_params(axis='both', which='major', labelsize=9)
        self.fig_pcg.subplots_adjust(left=0.12, bottom=0.15, right=0.95, top=0.9)
        self.fig_pcg.tight_layout(pad=3.0)
        self.pcg_layout.addWidget(self.canvas_pcg)
        self.layout_tab_pcg.addWidget(self.pcg_frame)
        self.layout_tab_pcg.addStretch(1)

        self.tabWidget.addTab(self.tab_pcg, "心音监测")
        self.gridLayout_6.addWidget(self.tabWidget, 3, 0, 1, 1)


        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")

        self.layout_tab4 = QtWidgets.QVBoxLayout(self.tab_4)
        self.layout_tab4.setContentsMargins(10, 10, 10, 10)
        self.layout_tab4.setSpacing(15)


        self.scroll_area_waveform = QtWidgets.QScrollArea()
        self.scroll_area_waveform.setWidgetResizable(True)
        self.scroll_area_waveform.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area_waveform.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_area_waveform.setStyleSheet("""
            QScrollArea {
                border: none;
                background-color: transparent;
            }
            QScrollBar:vertical {
                background-color: #F5F5F5;
                width: 12px;
                margin: 0px;
            }
            QScrollBar::handle:vertical {
                background-color: #BDBDBD;
                border-radius: 6px;
                min-height: 20px;
            }
            QScrollBar::handle:vertical:hover {
                background-color: #9E9E9E;
            }
        """)

        self.scroll_content_waveform = QtWidgets.QWidget()
        self.scroll_layout_waveform = QtWidgets.QVBoxLayout(self.scroll_content_waveform)
        self.scroll_layout_waveform.setContentsMargins(5, 5, 5, 5)
        self.scroll_layout_waveform.setSpacing(15)

        self.frame_carotid = QtWidgets.QFrame()
        self.frame_carotid.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_carotid.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.frame_carotid.setMinimumHeight(400)
        self.layout_carotid = QtWidgets.QVBoxLayout(self.frame_carotid)
        self.layout_carotid.setContentsMargins(10, 10, 10, 10)

        self.title_carotid = QtWidgets.QLabel("颈动脉波形")
        self.title_carotid.setStyleSheet("""
            QLabel {
                font-size: 14px;
                font-weight: bold;
                color: #0D47A1;
                padding: 8px;
                background-color: #E3F2FD;
                border-radius: 3px;
                text-align: center;
            }
        """)
        self.title_carotid.setAlignment(QtCore.Qt.AlignCenter)
        self.layout_carotid.addWidget(self.title_carotid)

        self.fig_carotid = Figure(figsize=(12, 6), dpi=100)
        self.canvas_carotid = FigureCanvas(self.fig_carotid)
        self.ax_carotid = self.fig_carotid.add_subplot(111)
        self.ax_carotid.set_title("", fontsize=12)
        self.ax_carotid.grid(True, which='both', alpha=0.3)
        self.ax_carotid.tick_params(axis='both', which='major', labelsize=9)
        self.fig_carotid.tight_layout(pad=3.0)
        self.layout_carotid.addWidget(self.canvas_carotid)

        self.scroll_layout_waveform.addWidget(self.frame_carotid)

        self.frame_femoral = QtWidgets.QFrame()
        self.frame_femoral.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_femoral.setStyleSheet("""
            QFrame {
                background-color: white;
                border-radius: 5px;
                border: 1px solid #E0E0E0;
            }
        """)
        self.frame_femoral.setMinimumHeight(400)
        self.layout_femoral = QtWidgets.QVBoxLayout(self.frame_femoral)
        self.layout_femoral.setContentsMargins(10, 10, 10, 10)

        self.title_femoral = QtWidgets.QLabel("股动脉波形")
        self.title_femoral.setStyleSheet("""
            QLabel {
                font-size: 14px;
                font-weight: bold;
                color: #0D47A1;
                padding: 8px;
                background-color: #E3F2FD;
                border-radius: 3px;
                text-align: center;
            }
        """)
        self.title_femoral.setAlignment(QtCore.Qt.AlignCenter)
        self.layout_femoral.addWidget(self.title_femoral)
        self.fig_femoral = Figure(figsize=(12, 6), dpi=100)
        self.canvas_femoral = FigureCanvas(self.fig_femoral)
        self.ax_femoral = self.fig_femoral.add_subplot(111)
        self.ax_femoral.set_title("", fontsize=12)
        self.ax_femoral.grid(True, alpha=0.3)
        self.ax_femoral.tick_params(axis='both', which='major', labelsize=9)
        self.fig_femoral.tight_layout(pad=3.0)
        self.layout_femoral.addWidget(self.canvas_femoral)
        self.scroll_layout_waveform.addWidget(self.frame_femoral)
        self.scroll_layout_waveform.addStretch(1)
        self.scroll_area_waveform.setWidget(self.scroll_content_waveform)
        self.layout_tab4.addWidget(self.scroll_area_waveform)
        self.tabWidget.addTab(self.tab_4, "颈股动脉波形")
        self.gridLayout_6.addWidget(self.tabWidget, 4, 0, 1, 1)

        
        

        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout_6.addWidget(self.tabWidget, 6, 0, 1, 1)
        self.pdf_preview_area = QtWidgets.QTextBrowser(self.tab_5)
        self.pdf_preview_area.setStyleSheet("""
            QTextBrowser {
                background-color: white;
                border: 1px solid #BBDEFB;
                border-radius: 4px;
                font-family: "Microsoft YaHei", "SimHei";
                font-size: 10px;
            }
            """)
        self.pdf_preview_area.setPlaceholderText("点击'查看预览'按钮创建检测报告预览")
        self.gridLayout_15.addWidget(self.pdf_preview_area, 0, 0, 1, 1)

        # 按钮框架
        self.report_button_frame = QtWidgets.QFrame(self.tab_5)
        self.report_button_frame.setMaximumHeight(60)
        self.gridLayout_15.addWidget(self.report_button_frame, 1, 0, 1, 1)

        # 按钮布局
        self.report_button_layout = QtWidgets.QHBoxLayout(self.report_button_frame)
        self.report_button_layout.addStretch()

        # 查看预览按钮
        self.preview_report_btn = QtWidgets.QPushButton("查看预览")
        self.preview_report_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.preview_report_btn.setMaximumSize(QtCore.QSize(120, 40))
        self.preview_report_btn.setStyleSheet("""
            QPushButton {
                background-color: #1E88E5;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 8px 16px;
                font-size: 12px;
            }
            QPushButton:hover {
                background-color: #1976D2;
            }
            QPushButton:pressed {
                background-color: #1565C0;
            }
            QPushButton:disabled {
                background-color: #BBDEFB;
                color: #666;
            }
        """)
        self.report_button_layout.addWidget(self.preview_report_btn)
        
        # 生成报告
        self.generate_pdf_btn = QtWidgets.QPushButton("生成报告")
        self.generate_pdf_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.generate_pdf_btn.setMaximumSize(QtCore.QSize(120, 40))
        self.generate_pdf_btn.setStyleSheet("""
            QPushButton {
                background-color: #4CAF50;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 8px 16px;
                font-size: 12px;
                margin-left: 10px;
            }
            QPushButton:hover {
                background-color: #43A047;
            }
            QPushButton:pressed {
                background-color: #388E3C;
            }
            QPushButton:disabled {
                background-color: #C8E6C9;
                color: #666;
            }
        """)
        self.generate_pdf_btn.setEnabled(False)
        self.report_button_layout.addWidget(self.generate_pdf_btn)

        self.export_data_btn = QtWidgets.QPushButton("导出数据")
        self.export_data_btn.setMinimumSize(QtCore.QSize(120, 40))
        self.export_data_btn.setMaximumSize(QtCore.QSize(120, 40))
        self.export_data_btn.setStyleSheet("""
            QPushButton {
                background-color: #FF9800;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 8px 16px;
                font-size: 12px;
                margin-left: 10px;
            }
            QPushButton:hover {
                background-color: #F57C00;
            }
            QPushButton:pressed {
                background-color: #E65100;
            }
            QPushButton:disabled {
                background-color: #FFE0B2;
                color: #666;
            }
        """)
        self.export_data_btn.setEnabled(True)
        self.report_button_layout.addWidget(self.export_data_btn)
        self.export_data_btn.clicked.connect(self.export_to_excel)
        
        self.preview_report_btn.clicked.connect(self.generate_report)
        self.generate_pdf_btn.clicked.connect(self.generate_pdf_by_measurement_id)

        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_16.setObjectName("gridLayout_16")

        self.search_frame = QtWidgets.QFrame(self.tab_6)
        self.search_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search_frame.setStyleSheet("background-color: #E3F2FD; border-radius: 5px;")
        self.gridLayout_16.addWidget(self.search_frame, 0, 0, 1, 1)

        self.search_layout = QtWidgets.QHBoxLayout(self.search_frame)
        self.search_layout.setObjectName("search_layout")

        # 患者ID搜索
        self.patient_id_search_label = QtWidgets.QLabel("患者ID:", self.search_frame)
        self.patient_id_search_label.setMinimumSize(QtCore.QSize(60, 30))
        self.search_layout.addWidget(self.patient_id_search_label)

        self.patient_id_search_edit = QtWidgets.QLineEdit(self.search_frame)
        self.patient_id_search_edit.setMinimumSize(QtCore.QSize(150, 30))
        self.patient_id_search_edit.setStyleSheet("background-color: white; border-radius: 3px;")
        self.search_layout.addWidget(self.patient_id_search_edit)

        # 日期范围搜索
        self.date_from_label = QtWidgets.QLabel("从:", self.search_frame)
        self.search_layout.addWidget(self.date_from_label)

        self.date_from_edit = QtWidgets.QDateEdit(self.search_frame)
        self.date_from_edit.setCalendarPopup(True)
        self.date_from_edit.setDate(QtCore.QDate.currentDate())
        self.date_from_edit.setStyleSheet("background-color: white; border-radius: 3px;")
        self.search_layout.addWidget(self.date_from_edit)

        self.date_to_label = QtWidgets.QLabel("到:", self.search_frame)
        self.search_layout.addWidget(self.date_to_label)

        self.date_to_edit = QtWidgets.QDateEdit(self.search_frame)
        self.date_to_edit.setCalendarPopup(True)
        self.date_to_edit.setDate(QtCore.QDate.currentDate())
        self.date_to_edit.setStyleSheet("background-color: white; border-radius: 3px;")
        self.search_layout.addWidget(self.date_to_edit)

        # 搜索按钮
        self.search_btn = QtWidgets.QPushButton("搜索", self.search_frame)
        self.search_btn.setMinimumSize(QtCore.QSize(80, 30))
        self.search_btn.setStyleSheet("""
            QPushButton {
                background-color: #2196F3;
                border-radius: 5px;
                color: white;
                font-weight: bold;
                padding: 6px 12px;
            }
            QPushButton:hover {
                background-color: #1976D2;
            }
            QPushButton:pressed {
                background-color: #1565C0;
            }
        """)
        self.search_btn.clicked.connect(self.load_history_records)
        self.search_layout.addWidget(self.search_btn)

        # 病例展示表格
        self.history_table = QtWidgets.QTableWidget(self.tab_6)
        self.history_table.setColumnCount(4)  # ID, 姓名, 日期, 操作1
        self.history_table.setHorizontalHeaderLabels(["体检号", "姓名", "检测日期", "查看报告"])
        self.history_table.setStyleSheet("""
            QTableWidget {
                background-color: white;
                border: 1px solid #BBDEFB;
                border-radius: 5px;
            }
            QHeaderView::section {
                background-color: #1E88E5;
                color: white;
                padding: 5px;
                border: none;
            }
        """)
        self.history_table.horizontalHeader().setStretchLastSection(True)
        self.history_table.verticalHeader().setVisible(False)
        self.history_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.history_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.gridLayout_16.addWidget(self.history_table, 1, 0, 1, 1)

        # 添加tab到tabWidget
        self.tabWidget.addTab(self.tab_6, "历史病例")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.tabWidget.tabBar().setStyleSheet("QTabBar::tab { width: 100px; }")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "动脉硬化检测系统"))
        self.user_group.setTitle(_translate("Form", "患者信息管理"))
        self.name_label.setText(_translate("Form", "姓名："))
        self.patient_id_label.setText(_translate("Form", "体检号："))
        self.outpatient_id_label.setText(_translate("Form", "门诊号："))
        self.inpatient_id_label.setText(_translate("Form", "住院号："))
        self.height_label.setText(_translate("Form", "身高(cm)："))
        self.weight_label.setText(_translate("Form", "体重(kg)："))
        self.age_label.setText(_translate("Form", "年龄："))
        self.gender_label.setText(_translate("Form", "性别："))
        self.save_user_btn.setText(_translate("Form", "保存"))
        self.query_user_btn.setText(_translate("Form", "查询"))
        self.clear_user_btn.setText(_translate("Form", "清空"))
        self.groupBox.setTitle(_translate("Form", "设备连接"))
        self.label_2.setText(_translate("Form", "串口："))
        self.label_3.setText(_translate("Form", "波特率："))
        self.connect_btn.setText(_translate("Form", "连接"))
        self.status_label.setText(_translate("Form", "未连接"))
        self.box_frame_rate.setTitle(_translate("Form", "采样频率（帧/秒）："))
        self.groupBox_2.setTitle(_translate("Form", "测量操作"))
        self.groupBox_3.setTitle(_translate("Form", "四路血压检测"))
        self.groupBox_5.setTitle(_translate("Form", "四肢动脉和心电心音同步检测"))
        self.groupBox_6.setTitle(_translate("Form", "颈股动脉倍数查询"))
        self.groupBox_4.setTitle(_translate("Form", "测量指令"))
        self.groupBox_7.setTitle(_translate("Form", "颈股动脉放大倍数调节"))
        self.groupBox_8.setTitle(_translate("Form", "颈股动脉同步检测"))

        self.checkBox1.setText(_translate("Form", "左上肢"))
        self.checkBox2.setText(_translate("Form", "左下肢"))
        self.checkBox3.setText(_translate("Form", "右上肢"))
        self.checkBox4.setText(_translate("Form", "右下肢"))
        self.checkBox5.setText(_translate("Form", "四肢动脉和心电心音检测"))
        self.checkBox6.setText(_translate("Form", "颈动脉和股动脉"))
        self.start_btn.setText(_translate("Form", "开始测量"))
        self.stop_btn.setText(_translate("Form", "停止测量"))
        self.clear_btn.setText(_translate("Form", "清除数据"))
        self.double_mode_btn.setText(_translate("Form","双模式测量"))
        self.label_14.setText(_translate("Form", "左上肢："))
        item = self.tableWidget1.horizontalHeaderItem(0)
        item.setText(_translate("Form", "收缩压"))
        item = self.tableWidget1.horizontalHeaderItem(1)
        item.setText(_translate("Form", "舒张压"))
        item = self.tableWidget1.horizontalHeaderItem(2)
        item.setText(_translate("Form", "心率"))
        self.label_15.setText(_translate("Form", "左下肢："))
        item = self.tableWidget2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "收缩压"))
        item = self.tableWidget2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "舒张压"))
        item = self.tableWidget2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "心率"))
        self.label_16.setText(_translate("Form", "右上肢："))
        item = self.tableWidget3.horizontalHeaderItem(0)
        item.setText(_translate("Form", "收缩压"))
        item = self.tableWidget3.horizontalHeaderItem(1)
        item.setText(_translate("Form", "舒张压"))
        item = self.tableWidget3.horizontalHeaderItem(2)
        item.setText(_translate("Form", "心率"))
        self.label_17.setText(_translate("Form", "右下肢："))
        item = self.tableWidget4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "收缩压"))
        item = self.tableWidget4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "舒张压"))
        item = self.tableWidget4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "心率"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "四路血压数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "四肢波形"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "颈股动脉波形"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "报告生成"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "历史病例"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_inflation_process), _translate("Form", "测量过程"))
        self.inflation_display_text.setPlaceholderText(_translate("Form", "打气过程中的血压值将显示在这里..."))



        



        